name: Deploy EC2 Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EC2_SSH_KEY }}
          aws-region: us-east-1  # Escolha a região que preferir

      - name: Launch EC2 instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-0c55b159cbfafe1f0 \  # AMI Ubuntu
            --count 1 \
            --instance-type t2.micro \
            --key-name lab_git \
            --query 'Instances[0].InstanceId' \
            --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

      - name: Wait for instance to be in running state
        run: |
          aws ec2 wait instance-running --instance-ids ${{ env.INSTANCE_ID }}

      - name: Output instance details
        run: |
          aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }}
