# Nome do fluxo de trabalho
name: Deploy EC2 Ubuntu

# Gatilho: Quando houver um push na branch principal
on:
  push:
    branches:
      - main 
jobs:
  # Definição do job
  deploy:
    # Ambiente onde o job será executado
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar as credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_KEY_ID }}  # ID da chave de acesso AWS
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}  # Chave secreta de acesso AWS
          aws-region: us-east-1  # Região da AWS (pode ser alterada conforme necessário)
      # Paso 3 : Start Instance
      - name: Start EC2 Instance
        run: |
          aws ec2 start-instances --instance-ids i-068d63f5f422e2a8b
          echo "Instance started successfully."

